---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(reshape2)
library(data.table)
library(stringi)
library(scales)
```

```{r}
#Load data
cbop_all <- readRDS('data\\cbop_all.rds')
model <- readRDS('data\\model.rds')
cbop_vec <- readRDS('data\\cbop_vec.rds')
stats_tab <-readRDS('data\\stats_tab.rds')
```

```{r}
#Table for stats - model
stats_tab <- rbind(stats_tab, data.table(error_type = c('Third error - missing values', 'Third error - invalid offers')), fill = TRUE)
```

```{r}
#Function to prepare data for further analysis
prepare_data <- function(CBOP_year) {
  
  CBOP_year <- CBOP_year %>% 
  mutate(czas_dostepnosci = poz_ofertaWaznaDo - poz_dataPrzyjZglosz,
         czas_dostepnosci_przedzial = case_when(
                                        czas_dostepnosci < 25 ~ "<25",
                                        czas_dostepnosci < 50 ~ "<25; 50)",
                                        czas_dostepnosci < 75 ~ "<50; 75)",
                                        czas_dostepnosci < 100 ~ "<75; 100)",
                                        TRUE ~ ">100"))

  CBOP_year <- CBOP_year %>% 
    filter(
      !is.na(poz_grupaZawodu) & !is.na(poz_lWolnychMiejsc) & 
             !is.na(war_wojewodztwo) & !is.na(czas_dostepnosci_przedzial) & 
             !is.na(klasa) & !is.na(sek) & !(poz_grupaZawodu %in% c('6','0'))
           ) 
  
  CBOP_year$war_wojewodztwo <- stri_trans_general(CBOP_year$war_wojewodztwo, 'pl-ascii')
  
  vector_stat <- append(c(), sum(CBOP_year$poz_lWolnychMiejsc, na.rm = TRUE))
  
  probability <- predict(model, CBOP_year, type = 'response')
  CBOP_year <- cbind(CBOP_year, probability)
  CBOP_year$predict_vacancy <- CBOP_year$poz_lWolnychMiejsc * CBOP_year$probability
  
  vector_stat <- append(vector_stat, sum(CBOP_year$predict_vacancy, na.rm = TRUE))
  
  return(list("cbop"= CBOP_year, "stats" = vector_stat))
}
```

```{r}
#Prepare data and apply model
for (i in 1:11) {
  result <- prepare_data(cbop_vec[[i]])
  cbop_vec[[i]] <- result$cbop
  stats_tab[7:8, i + 1] <- result$stats
}

result <- prepare_data(cbop_all)
cbop_all <- result$cbop
stats_tab[7:8, 13] <- result$stats
```

```{r}
#Stats table
stats_tab_n <- cbind(stats_tab[2:8,1], stats_tab[1:7,2:13] - stats_tab[2:8,2:13])

#Table for the scale of error and number of free vacancies
stats_tab_error <- stats_tab_n
stats_tab_error[1:3,2:13] <- cumsum(stats_tab_n[1:3,2:13])
stats_tab_error[4:5,2:13] <- cumsum(stats_tab_n[4:5,2:13])
stats_tab_error[6:7,2:13] <- cumsum(stats_tab_n[6:7,2:13])
stats_tab_error <- stats_tab_error[c(3,5,7),]
stats_tab_error[,1] <- c('n1', 'n2', 'n3')
names(stats_tab_error)[1] <- 'error_type'
stats_tab_error <- rbind(stats_tab[1,], stats_tab_error, stats_tab[8,])
stats_tab_error[5,1] <- 'Final value'
stats_tab_error <- as.data.frame(t(stats_tab_error))
colnames(stats_tab_error) <- stats_tab_error[1,]
stats_tab_error <- stats_tab_error[-1,]

#Table for the size of error - percentage
stats_tab_all_perc <- percent(round(as.numeric(unlist(prop.table(stats_tab_n[, 13]))),digit = 4))
stats_tab_all_perc <- as.data.frame(cbind(stats_tab_n[, 1], stats_tab_all_perc))
```

```{r}
#Number of vacancies per month - function
n_vacancy_plot <- function(CBOP_year, startDate, endDate) {
  months_analysis <- seq(ym(startDate), ym(endDate), by = 'month')
  months_interval <- interval(months_analysis, months_analysis + months(1) - days(1))

  n_vacancy <- data.frame(date = months_interval, type = 0, vacancy = 0)
  n_vacancy <- rbind(n_vacancy, n_vacancy)

  for (i in 1:length(months_interval)) {
     n_vacancy[i, 2:3] <- c('observed',
       sum(CBOP_year$poz_lWolnychMiejsc[which(int_overlaps(
         interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo),
         months_interval[i]))]))
     n_vacancy[i+length(months_interval), 2:3] <- c('estimated',
       sum(CBOP_year$predict_vacancy[which(int_overlaps(
         interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo),
         months_interval[i]))]))
  }
  
  n_vacancy[,1] <- ym(format(months_analysis, format = "%Y/%m"))
  n_vacancy[,3] <- as.numeric(n_vacancy[,3])/1000
  
  n_plot <- ggplot(data = n_vacancy, aes(x = date, y = vacancy, group = type)) +
    geom_line(aes(color = type)) +
    geom_point(aes(color = type)) +
    theme_bw() +
    scale_color_manual(values=c('grey50','black')) +
    theme(plot.title = element_blank(), axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = 'bottom',
          legend.title = element_blank(),
          text = element_text(size = 25),
          plot.margin = margin(r = 8, t = 2)) +
    scale_x_date(date_labels = "%m/%y")
    
    
  return(n_plot)
}
```

```{r}
#Number of vacancies per month
n_vacancy_plot_all <- n_vacancy_plot(cbop_all, "2020/10", "2023/03")
print(n_vacancy_plot_all)
```

```{r}
# Ocupational groups based on job code

#1 Public officials, officers, managers
#2 Professionals - high positions
#3 Technicians and associate professionals
#4 Office workers
#5 Service & sales workers
#6 Farmers, gardeners, fishermen 
#7 Craft and related trade workers
#8 Plant and machine operators and assemblers
#9 Employees performing simple work
```

```{r}
#Demand for specific job groups - function
n_occup_group_plot <- function(CBOP_year, startDate, endDate) {
  months_analysis <- seq(ym(startDate), ym(endDate), by = 'month')   
  months_interval <- interval(months_analysis, months_analysis + months(1) - days(1))
  
  occupation_code <-  data.frame(months = months_interval, type = 0, group1 = 0,
                                 group2 = 0, group3 = 0, group4 = 0, group5 = 0,
                                 group6 = 0, group7 = 0, group8 = 0, group9 = 0)
  
  colnames(occupation_code) <- c('months', 'type', '1 - Public officials', 
                                 '2 - Professionals', '3 - Technicians', 
                                 '4 - Office workers', '5 - Service workers', 
                                 '6 - Farmers', '7 - Craft workers', 
                                 '8 - Machine operators', '9 - Simple work employee')
  
  occupation_code <- rbind(occupation_code, occupation_code)
  
  for (i in 1:length(months_interval)) {
    for (k in 1:9) {
      occupation_code[i, k+2] <- 
        sum(CBOP_year$poz_lWolnychMiejsc[which(int_overlaps(
          interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
          months_interval[i]) & CBOP_year$poz_grupaZawodu == as.character(k))]) 
      occupation_code[i, 2] <- 'observed'
      occupation_code[i+length(months_interval), k+2] <- 
        sum(CBOP_year$predict_vacancy[which(int_overlaps(
          interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
          months_interval[i]) & CBOP_year$poz_grupaZawodu == as.character(k))]) 
      occupation_code[i+length(months_interval), 2] <- 'estimated'
    }
  }
  
  occupation_code[,1] <- ym(format(months_analysis, format = "%Y/%m"))
  occupation_code[,3:11] <- occupation_code[,3:11]/1000
  
  occupation_code <- melt(occupation_code, id.vars = c("months", "type"))

  demand_occup_plot <- ggplot(data = occupation_code, 
                              aes(x = months, y = value, group = type)) +
    geom_line(aes(color = type)) +
    geom_point(aes(color = type)) +
    theme_bw() +
    scale_color_manual(values=c('grey50','black')) +
    theme(plot.title = element_blank(), 
          axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = 'bottom',
          legend.title = element_blank(),
          text = element_text(size = 25),
          plot.margin = margin(r = 16, t = 2)) +
    facet_wrap(~variable) +
    scale_x_date(date_labels = "%m/%y")
  
 return(demand_occup_plot) 
}
```

```{r}
#Demand for specific job groups
demand_og_plot_all <- n_occup_group_plot(cbop_all, "2020/10", "2023/03")
print(demand_og_plot_all)
```

```{r}
#Number of vacancies by province - function
n_province <- function(CBOP_year, startDate, endDate) {
  months_analysis <- seq(ym(startDate), ym(endDate), by = 'month')   
  months_interval <- interval(months_analysis, months_analysis + months(1) - days(1))
  
  occupancies_provinces <- data.frame(months = months_interval, type = 0,
                                      dolnoslaskie = 0, kujawsko_pomorskie = 0,
                                      lubelskie = 0, lubuskie = 0, lodzkie = 0,
                                      malopolskie  = 0, mazowieckie = 0, 
                                      opolskie = 0, podkarpackie = 0, podlaskie = 0,
                                      pomorskie = 0, slaskie = 0, 
                                      swietokorzyskie = 0, warminisko_mazurskie = 0,
                                      wielkopolskie = 0, zachodniopomorskie = 0)
  
  occupancies_provinces <- rbind(occupancies_provinces, occupancies_provinces)
  
  for (i in 1:length(months_interval)) {
    for (k in 1:16) {
      occupancies_provinces[i, k + 2] <-
        sum(CBOP_year$poz_lWolnychMiejsc[which(int_overlaps( 
          interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
          months_interval[i]) & 
            CBOP_year$war_kodWojewodztwa == str_pad(as.character(k*2), 2, pad = "0"))])
      occupancies_provinces[i, 2] <- 'observed'
      occupancies_provinces[i+length(months_interval), k + 2] <-
        sum(CBOP_year$predict_vacancy[which(int_overlaps( 
          interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
          months_interval[i]) & 
            CBOP_year$war_kodWojewodztwa == str_pad(as.character(k*2), 2, pad = "0"))])
      occupancies_provinces[i+length(months_interval), 2] <- 'estimated'
    }
  }
  
  occupancies_provinces[,1] <- ym(format(months_analysis, format = "%Y/%m"))
  occupancies_provinces[,3:18] <- occupancies_provinces[,3:18]/1000
  colnames(occupancies_provinces) <- c('months', 'type', 'dolnoslaskie', 
                                       'kujawsko-pomorskie',
                                        'lubelskie', 'lubuskie', 'lodzkie',
                                        'malopolskie', 'mazowieckie', 'opolskie',
                                        'podkarpackie', 'podlaskie', 'pomorskie',
                                        'slaskie', 'swietokrzyskie', 
                                        'warminsko-mazurskie', 'wielkopolskie',
                                        'zachodniopomorskie')
  occupancies_provinces <- melt(occupancies_provinces, id.vars = c("months", "type"))

  province_plot <- ggplot(data = occupancies_provinces, 
                          aes(x = months, y = value, group = type)) +
    geom_line(aes(color = type)) +
    geom_point(aes(color = type)) +
    theme_bw() +
    scale_color_manual(values=c('grey50','black')) +
    facet_wrap(~variable) +
    theme(plot.title = element_blank(), 
          axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = 'bottom',
          legend.title = element_blank(),
          text = element_text(size = 23),
          plot.margin = margin(r = 16, t =2)) +
    scale_x_date(date_labels = "%m/%y")
  
  return(province_plot)
}
```

```{r}
#Number of vacancies by province
province_plot_all <- n_province(cbop_all, "2020/10", "2023/03")
print(province_plot_all)
```

```{r}
#Number of vacancies grouped by class - function
n_class_plot <- function(CBOP_year, startDate, endDate) {
  months_analysis <- seq(ym(startDate), ym(endDate), by = 'month')   
  months_interval <- interval(months_analysis, months_analysis + months(1) - days(1))
  
  class_tab <-  data.frame(months = months_interval, type = 0, groupM = 0,
                                 groupS = 0, groupD = 0)
  
  colnames(class_tab) <- c('months', 'type', 'M - small', 
                                 'S - Average', 'D - Big')
  
  class_tab <- rbind(class_tab, class_tab)
  class_type = c('M', 'S', 'D')
  
  for (i in 1:length(months_interval)) {
    for (k in 1:3) {
      class_tab[i, k+2] <- 
        sum(CBOP_year$poz_lWolnychMiejsc[which(int_overlaps(
          interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
          months_interval[i]) & CBOP_year$klasa == class_type[k])]) 
      class_tab[i, 2] <- 'observed'
      class_tab[i+length(months_interval), k+2] <- 
        sum(CBOP_year$predict_vacancy[which(int_overlaps(
          interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
          months_interval[i]) & CBOP_year$klasa == class_type[k])]) 
      class_tab[i+length(months_interval), 2] <- 'estimated'
    }
  }
  
  class_tab[,1] <- ym(format(months_analysis, format = "%Y/%m"))
  class_tab[,3:5] <- class_tab[,3:5]/1000
  
  class_tab <- melt(class_tab, id.vars = c("months", "type"))

  class_plot <- ggplot(data = class_tab, 
                              aes(x = months, y = value, group = type)) +
    geom_line(aes(color = type)) +
    geom_point(aes(color = type)) +
    theme_bw() +
    scale_color_manual(values=c('grey50','black')) +
    theme(plot.title = element_blank(), 
          axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = 'bottom',
          legend.title = element_blank(),
          text = element_text(size = 25),
          plot.margin = margin(r = 16, t =2)) +
    facet_wrap(~variable) +
    scale_x_date(date_labels = "%m/%y")
  
 return(class_plot) 
}
```

```{r}
#Number of vacancies grouped by class
class_plot <- n_class_plot(cbop_all, "2020/10", "2023/03")
print(class_plot)
```

```{r}
#Number of vacancies grouped by sector - function
n_sector_plot <- function(CBOP_year, startDate, endDate) {
  months_analysis <- seq(ym(startDate), ym(endDate), by = 'month')   
  months_interval <- interval(months_analysis, months_analysis + months(1) - days(1))
  
  sector_tab <-  data.frame(months = months_interval, type = 0, group1 = 0,
                                 group2 = 0)
  
  colnames(sector_tab) <- c('months', 'type', '1 - public', '2 - private')
  
  sector_tab <- rbind(sector_tab, sector_tab)
  
  for (i in 1:length(months_interval)) {
    for (k in 1:2) {
      sector_tab[i, k+2] <- 
        sum(CBOP_year$poz_lWolnychMiejsc[which(int_overlaps(
          interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
          months_interval[i]) & CBOP_year$sek == as.character(k))]) 
      sector_tab[i, 2] <- 'observed'
      sector_tab[i+length(months_interval), k+2] <- 
        sum(CBOP_year$predict_vacancy[which(int_overlaps(
          interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
          months_interval[i]) & CBOP_year$sek == as.character(k))]) 
      sector_tab[i+length(months_interval), 2] <- 'estimated'
    }
  }
  
  sector_tab[,1] <- ym(format(months_analysis, format = "%Y/%m"))
  sector_tab[,3:4] <- sector_tab[,3:4]/1000
  
  sector_tab <- melt(sector_tab, id.vars = c("months", "type"))

  sector_plot <- ggplot(data = sector_tab, 
                              aes(x = months, y = value, group = type)) +
    geom_line(aes(color = type)) +
    geom_point(aes(color = type)) +
    theme_bw() +
    scale_color_manual(values=c('grey50','black')) +
    theme(plot.title = element_blank(), 
          axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          axis.text.x = element_text(angle = 50, vjust = 1, hjust = 1),
          axis.ticks.x = element_blank(),
          legend.position = 'bottom',
          legend.title = element_blank(),
          text = element_text(size = 20),
          plot.margin = margin(r = 16, t =2)) +
    facet_wrap(~variable) +
    scale_x_date(date_labels = "%m/%y")
  
 return(sector_plot) 
}
```

```{r}
#Number of vacancies grouped by sector
sector_plot <- n_sector_plot(cbop_all, "2020/10", "2023/03")
print(sector_plot)
```

```{r}
#Number of vacancies offered for employees by every contracts type - function
n_every_contracts_plot <- function(CBOP_year, startDate, endDate, contracts) {
  months_analysis <- seq(ym(startDate), ym(endDate), by = 'month')   
  months_interval <- interval(months_analysis, months_analysis + months(1) - days(1))

  contract_type_years <- data.frame(months = months_interval, type = 0, u1 = 0, u2 = 0,
                                    u3 = 0, u4 = 0, u5 = 0)

  colnames(contract_type_years) <- append(c('months', 'type'), contracts[,1])
  contract_type_years <- rbind(contract_type_years, contract_type_years)

  for (k in 1:5) {
    for (i in 1:length(months_interval)) {
     contract_type_years[i, k+1] <-
       sum(CBOP_year$poz_lWolnychMiejsc[which(int_overlaps(   
         interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
         months_interval[i]) & CBOP_year$war_kodRodzajuZatrudnienia == contracts[k, 2])])
     contract_type_years[i, 2] <- 'observed'
     contract_type_years[i+length(months_interval), k+1] <-
       sum(CBOP_year$predict_vacancy[which(int_overlaps(   
         interval(CBOP_year$poz_dataUdostepnieniaOferty, CBOP_year$poz_ofertaWaznaDo), 
         months_interval[i]) & CBOP_year$war_kodRodzajuZatrudnienia == contracts[k, 2])])
     contract_type_years[i+length(months_interval), 2] <- 'estimated'
    }
  }
  
  contract_type_years[,1] <- ym(format(months_analysis, format = "%Y/%m"))
  contract_type_years[,3:7] <- contract_type_years[,3:7]/1000
  contract_type_years <- melt(contract_type_years, id.vars = c('months', 'type'))

  every_contracts_plot <- ggplot(data = contract_type_years, 
                               aes(x = months, y = value, group = type)) +
    geom_line(aes(color = type)) +
    geom_point(aes(color = type)) +
    theme_bw() + 
    facet_wrap(~variable, nrow = 3) +
    scale_color_manual(values=c('grey50','black')) +
    theme(plot.title = element_blank(), 
          axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          axis.text.x = element_text(angle = 50, vjust = 1, hjust = 1),
          axis.ticks.x = element_blank(),
          legend.position = 'bottom',
          legend.title = element_blank(),
          text = element_text(size = 20),
          plot.margin = margin(r = 16, t =2)) +
    scale_x_date(date_labels = "%m/%y")
  
  return(every_contracts_plot)
}
```

```{r}
#Number of vacancies offered for employees by contract type 
contracts <- data.frame(
  contract_type = c('Employment contract for a definite period', 'Employment contract for a trial period', 'Employment contract for an indefinite period', 'Contract for the time of performance of specific work', 'Substitute employment contract'), 
  contract_code = c("RPs005|12", "RPs005|13", "RPs005|11", "RPs005|18", "RPs005|22"))

# contract_plot <- list()
# for (k in 1:5) {
#   contract_plot[[k]] <- n_contract_plot(cbop_all, "2020/10", "2023/03",
#                                           contracts[k,])
#   print(contract_plot[k])
# }
# rm(k)

every_contracts_plot_all <- n_every_contracts_plot(cbop_all, "2020/10",
                                                   "2023/03", contracts)
print(every_contracts_plot_all)
```

